### ISSUE TITLE
metadata parsing failed

### ISSUE THREAD

**Issue by hyllm** [quietvoid/hdr10plus_parser#11]
Movie "IT: Chapter Two"... metadata parsing is failing with error.

`Reading parsed dynamic metadata... thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `9`', src\hdr10plus.rs:269:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.`

I was able to lock out the 50MB video segment, which is erroring (the rest of the movie is OK)

`https://wetransfer.com/downloads/fc79a8f341b93d15703999a99556cc9f20191202154301/8db1305e900829f57618dd2373b50d9020191202154301/e7a6ed`

**Comment by hyllm** [comment]
any news?

**Comment by quietvoid** [comment]
Spent a couple days trying fixes, haven't figured it out yet.

**Comment by quietvoid** [comment]
Should be fixed in 0.2.6

**Comment by hyllm** [comment]
Sorry... but think, it's not fixed.. :(
![screen](https://user-images.githubusercontent.com/33330694/72661527-77473d80-39db-11ea-9551-46613727e001.PNG)
